application: cookie
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: cookie.application
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest